name: Wake Up Site

on:
  schedule:
    - cron: "*/10 * * * *"  # This cron expression means every 5 minutes

jobs:
  wake_up:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP request to wake up the site
        run: |
          curl -s https://codequestapi.onrender.com/
